### ISSUE TITLE
apache2buddy not considering vcache

### ISSUE THREAD

**Issue by dthielking** [richardforth/apache2buddy#283] opened 2019-01-07 21:50 UTC
Hello,

first thank you for your effort writing this tool. It helps me allot.
I used it today on our heavily loaded web servers with Apache2 and Varnish. 
It is a 32Gb memory instance. I configured varnish (vcache) to cache all our requests on the instance. I tried to figure out how many workers I can spawn. So I issued apache2buddy.pl and it outputs following varnish line: `[ -- ] Varnish Detected => Using 7.44 MB of memory.` but this is only varnish and not its vcache.
I configure Varnish (vcache) to use 16Gb memory. 
Maybe it would be better du substract den configured vcache from the total memory to make better recommendations.

**Comment by richardforth** [comment] 2019-01-08 09:54
Hi Apache2buddy only detects what is actually being used by additional services, it doesnt care what you configured it to use. If I am not detecting the usage of the vcache, in ps output, please provide an example of how I can detect this (note that parsing any configuration files is not an option).

**Comment by dthielking** [comment] 2019-01-08 13:39
Hi @richardforth, I found a way to find the memory consumption of the vcache. 
The problem is it is not the command as you use in your code with -C for ps.
The cache is owned by the user vcache. 
I issued following command to get its complete ps output

> ps aux | grep vcache
> vcache   27009 30.7 58.5 29486828 18815824 ?   Sl   Jan07 408:01 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G

So that I now know what to filter I use following command to get its actually used mem

> ps -U vcache -o rss | grep -v RSS
> 18759136

Hope this solution is good to implement.

**Comment by richardforth** [comment] 2019-01-08 14:12
Unfortunately for me this isnt making much sense, as the stock installations of varnish show up just fine in ps -C as we are only interested in processes running called varnishd , so it should be picking up your /usr/sbin/varnishd process no matter the fact that its running as a user called vcache.

Can you run the following for me and let me know what you get back:

# ps auxfwww | grep varnishd

# ps -C varnishd

# pc -C varnishd -o rss | grep -v RSS

Also if you can,  run apache2buddy.pl in verbose mode and get me the varnish ouput:

# curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl - --verbose | grep -i varnish

Hopefully I will be able to make sense of whats gong on

**Comment by dthielking** [comment] 2019-01-08 14:37
I issued following
```
# perl apache2buddy.pl --verbose | grep -i varnish
VERBOSE: Varnish Detected
[ -- ] Varnish Detected => Using 7.25 MB of memory.
VERBOSE: Varnish Mem: 7.25
```

I also issue following
```
# ps aux | grep -i varnish
root     12846  0.0  0.0  13096   940 pts/2    S+   14:34   0:00 grep --color=auto -i varnish
varnish  26995  0.0  0.0 118992  7424 ?        Ss   Jan07   0:02 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G
vcache   27009 30.7 58.6 29486828 18844444 ?   Sl   Jan07 425:38 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G
```

**Comment by richardforth** [comment] 2019-01-08 14:53
and these as well please

```bash
# ps -C varnishd

# pc -C varnishd -o rss | grep -v RSS
```

**Comment by dthielking** [comment] 2019-01-08 15:10
Oh. Sorry did't see that.
```
# ps -C varnishd
  PID TTY          TIME CMD
26995 ?        00:00:02 varnishd

# ps -C varnishd -o rss | grep -v RSS
 7424

# ps auxfwww | grep varnishd
root     14102  0.0  0.0  13096   908 pts/0    S+   15:09   0:00                      \_ grep --color=auto varnishd
varnish  26995  0.0  0.0 118992  7424 ?        Ss   Jan07   0:02 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G
vcache   27009 30.7 57.7 29486828 18552600 ?   Sl   Jan07 436:03  \_ /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G
```

**Comment by richardforth** [comment] 2019-01-08 15:22
Interesting, I wonder if its only picking up the root one by default, not ones owned by other users. the ps output only appears to pick up the 7424 one, which is odd.

Can you confirm how you set it to run as vcache, and i'll do some testing this end.

If eh name vcache is arbitrary then i may not be able to do much but you are right, its shoudl be picking up that second process as well, and its not. Which is a cause of concern.

One thing you do have to bear in mind is that apache2buddy pretty much only works with stock installations, anything custom is likely to break its functionality. I usually recommend that peopl fork my work and createa custom version for their own uses, but this one is interesting, and I'd like to solve it.

**Comment by dthielking** [comment] 2019-01-08 15:35
As you can see in the varnish changelog for versions > 4.1 it sets it automatically.
https://varnish-cache.org/docs/4.1/whats-new/changes.html

**Comment by richardforth** [comment] 2019-01-08 15:41
Ah cool

Fair play, I may need to tweak some stuff for varnish 4,  I will have a play and let you know. Thanks for raising this issue! 

Kind Regards
Richard

**Comment by dthielking** [comment] 2019-02-04 19:40
Hey @richardforth any progress on that?

**Comment by richardforth** [comment] 2019-02-04 20:13
Hi

Its still on my to do list. Sorry I have been slammed with work. But I will
look into it when I get some free time.

Apache2buddy isn't funded so I get to it when I can.

I will certainly look into this for you.

Kind regards
Richard

**Comment by dthielking** [comment] 2019-02-05 09:08
Hi,
no problem, I just wanted to ask. 
If I can provide more information, just let me know.

Kind regards
Daniel

**Comment by richardforth** [comment] 2019-02-05 15:46
Hi,

What OS are you running? I just tried to replicate this on CentOS7 but failed. not sure if the vcache thig is an ubuntuism. They like to do thing differently it seems.

Kind Regards
Richard

256 stock malloc ona 1gb test server
```
[ -- ] Varnish Detected => Using 176.93 MB of memory.

[root@server-01 ~]# ps auxfwww | grep varnish
root      5644  0.0  0.0 112708   936 pts/0    S+   15:41   0:00          \_ grep --color=auto varnish
varnish   5161  0.1  8.7 122856 88076 ?        SLs  15:40   0:00 /usr/sbin/varnishd -P /var/run/varnish.pid -f /etc/varnish/default.vcl -a :6081 -T 127.0.0.1:6082 -S /etc/varnish/secret -s malloc,256M
varnish   5162  0.2  9.2 270672 93092 ?        Sl   15:40   0:00  \_ /usr/sbin/varnishd -P /var/run/varnish.pid -f /etc/varnish/default.vcl -a :6081 -T 127.0.0.1:6082 -S /etc/varnish/secret -s malloc,256M
[root@server-01 ~]# ps auxfwww | grep vcache
root      5660  0.0  0.0 112708   936 pts/0    S+   15:42   0:00          \_ grep --color=auto vcache

```

**Comment by dthielking** [comment] 2019-02-06 09:12
Yes you are totally right. I'm using Ubuntu 14.04 and 18.04 with Varnish 5.1.3.

**Comment by richardforth** [comment] 2019-02-06 09:15
Ok cool. I'll try and run some more tests later on when I get a chance - once I can replicate it in my environment I can start coding for it to pick up the vcache. thanks for getting back to me :)

**Comment by dthielking** [comment] 2019-02-06 09:17
Sure! Great thanks to you for helping me out.

**Comment by richardforth** [comment] 2019-02-09 11:30
Just to let you know I got a cloudserver with 18.04 and varnish 5.2.1-1 - hopefully were cooking on gas now. i will let you know how it goes.

**Comment by dthielking** [comment] 2019-02-09 11:39
Great! Let me know when you need support. After you got something I can test it on Ubuntu 14.04.

**Comment by richardforth** [comment] 2019-02-09 13:35
good news is out-of -the box liek straught after apt0-get install I can see the issue exactly as described:


```bash
root@ubu1804:~# ps auxfwww | grep varn
root     10010  0.0  0.1  14852  1096 pts/1    S+   13:33   0:00  |       \_ grep --color=auto varn
vcache    6447  0.0  0.4  36996  4232 ?        SLs  11:25   0:00 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
vcache    6543  0.0  0.6 260980  6208 ?        SLl  11:25   0:01  \_ /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
varnish+  6762  0.3  0.0  99136   168 ?        Ss   11:25   0:24 /usr/bin/varnishncsa -a -w /var/log/varnish/varnishncsa.log -D -P /run/varnishncsa/varnishncsa.pid
root@ubu1804:~#

```

Now I just have to work out how exactly I am going to code around this....

*thinkingface

**Comment by richardforth** [comment] 2019-02-09 13:42
```perl
	# Detect Varnish
	our $varnish_detected = 0;
	$varnish_detected = `ps -C varnishd -o rss | grep -v RSS`;
	if ( $varnish_detected ) { 
		if ($VERBOSE) { print "VERBOSE: Varnish Detected\n" }
		our $servicefound_flag = 1;
		if ( ! $NOINFO ) { show_info_box(); print "${CYAN}Varnish${ENDC} Detected => " }
		# Get varnish Memory Usage
		our $varnish_memory_usage_mbytes = get_service_memory_usage_mbytes("varnishd");
		if ( ! $NOINFO ) { print "Using ${CYAN}$varnish_memory_usage_mbytes MB${ENDC} of memory.\n" }
	} else {
		if ($VERBOSE) { print "VERBOSE: Varnish NOT Detected\n" }
		our $varnish_memory_usage_mbytes = 0;
	}
```

Heres what we are looking at in term of the current code. I'll be staring at this for a while now until something hits me. If you come up with any ideas I am open.  but we need to add extra logic in to search for vcache and take that into account as well....and its supposed to be simple - after all this isnt varnishbuddy....KISS - keep it simple stupid.

What about an "egrep" so we capture either both or one depending on whats found?


or

are there additional switched we can use to alter this line:

```perl
$varnish_detected = `ps -C varnishd -o rss | grep -v RSS`;
```

as i think just -C only looks for root-owned processes......


would

```perl
$varnish_detected = `ps -aC varnishd -o rss | grep -v RSS`;
```

work?

hmmm

*puffs on imaginary cigar and looks out of his imaginary window in deep thought........

**Comment by richardforth** [comment] 2019-02-09 13:43
```bash
root@ubu1804:~# ps -C varnishd -o rss | grep -v RSS
 4232
root@ubu1804:~# ps -aC varnishd -o rss | grep -v RSS
 4232
 1544
 1092
root@ubu1804:~#
```

**Comment by richardforth** [comment] 2019-02-09 13:44
thsi might be an easier fix than i thought

can you give this a try:

```bash
ps -aC varnishd -o rss | grep -v RSS
```

**Comment by richardforth** [comment] 2019-02-09 13:45
oh um but then theres this...

get_service_memory_usage_mbytes("varnishd")

the rabbit hole deepens...

**Comment by richardforth** [comment] 2019-02-09 13:47
```perl
sub get_service_memory_usage_mbytes {
	my ( $svc )  = @_;
	my @usage_by_pids = `ps -C $svc -o rss | grep -v RSS`;
	our $usage_mbytes = 0;
	foreach my $proc (@usage_by_pids) {
		our $usage_mbytes += $proc / 1024;
	}
	our $usage_mbytes = round($usage_mbytes);
	return $usage_mbytes;
}
```

ah no thats fine

I can just add -a flag to that too

**Comment by richardforth** [comment] 2019-02-09 13:48
can you give this a try:

```shell
ps -aC varnishd -o rss | grep -v RSS
```

And then hopefully it give you what you expect in terms of memory usage  - it will give you it per process.

All the function does then is aggregates them into a single figure which will hopefully be a little more realistic for you.

**Comment by dthielking** [comment] 2019-02-09 17:05
Hello I tried adding:
`ps -aC varnishd -o rss | grep -v RSS`
to the code but it only shows the varnishd process. 
I also issued it on the cmd line:
```
ps -aC varnishd -o rss,command
  RSS COMMAND
 7544 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/
 1524 ps -aC varnishd -o rss,command
```

**Comment by richardforth** [comment] 2019-02-09 19:28
Thst doesn't look like what i asked you to run

**Comment by dthielking** [comment] 2019-02-09 19:36
You asked me to run this:
```
ps -aC varnishd -o rss | grep -v RSS
 7544
 1536
 1088
```

**Comment by richardforth** [comment] 2019-02-09 19:52
yes thats right.

ps -aC varnishd -o rss | grep -v RSS

if you drop the -a you'll get the one proc  instead of the three proc's memory consumption.

in the code it turns out theres a couple of places this needs to be changed:
https://github.com/richardforth/apache2buddy/blob/abf3b526daf3fd39128528d0ddfc7b00978a0c60/apache2buddy.pl#L2415
Once in the the place where it first calls the function (get_service_memory_usage_mbytes), 


and then again in the function itself (get_service_memory_usage_mbytes)
https://github.com/richardforth/apache2buddy/blob/abf3b526daf3fd39128528d0ddfc7b00978a0c60/apache2buddy.pl#L2371

note that it detect residential memory (actually used memory) not "configured" memory.

**Comment by richardforth** [comment] 2019-02-09 19:55
I have a sneaky feeeing youre still expecting me to detect if youve set the cache to 16G even if its not in use, But apache2buddy was never built to parse config files of other programs on the server, it only cares about what memory is being used at the current moment in time as shown in the RSS column of the ps output.

**Comment by richardforth** [comment] 2019-02-09 19:57
whereas previously you can see without the -a it was only picking up the one proc run by root, not its picking up the other two owned by the vcache user.


> ```shell
> root@ubu1804:~# ps -C varnishd -o rss | grep -v RSS
>  4232
> root@ubu1804:~# ps -aC varnishd -o rss | grep -v RSS
>  4232
>  1544
>  1092
> root@ubu1804:~#
> ```

Hope that makes more sense?

**Comment by richardforth** [comment] 2019-02-09 20:18
here is a link to the commit so you can see what I changed:

https://github.com/richardforth/apache2buddy/commit/62783b4d58e090459afa0a7ee83da4201b4f796a


Heres the command you can run to test staging:

```bash
curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
```


if you want to compare with live (master branch) which doesnt have the change in yet:

```bash
curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl
```

**Comment by dthielking** [comment] 2019-02-09 20:19
No I do not exprect that apache2buddy will output 16Gb only because it's configured.
I executed:
`ps -aC varnishd -o rss | grep -v RSS`
But the returened values are one for varnishd, for the ps command and for the grep command. 
That is why you get back three values. 

If you execute following you will see what actually comes back, And you will see no vcache. ;-)
```
ps -aC varnishd -o rss,command | grep -v RS
 7544 /usr/sbin/varnishd -a :6081 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,16G
 1504 ps -aC varnishd -o rss,command
```

**Comment by richardforth** [comment] 2019-02-09 20:22
aah ok

sorry i was barking up the wrong tree - I guess that didnt do what i expected it to do.

I'll test some more. sorry about that! i thought we nailed it.

**Comment by richardforth** [comment] 2019-02-09 20:39
ok now I understand why you posted that other random command, you were trying to show me something - my bad there! 

I totally misunderstood

**Comment by richardforth** [comment] 2019-02-09 20:41
interesting, as you say that -a has actually caused more problems than it solved.

[ -- ] Your PHP Memory Limit (Per-Process) is 128M.
[ -- ] MySQL Detected => Using 18.30 MB of memory.
[ -- ] Java Detected => Using 18.32 MB of memory.
[ -- ] Varnish Detected => Using 22.48 MB of memory.
[ -- ] Redis Detected => Using 18.33 MB of memory.
[ -- ] Memcache Detected => Using 18.39 MB of memory.
[ -- ] PHP-FPM Detected => Using 18.33 MB of memory.
[ -- ] Gluster Detected => Using 54.94 MB of memory.
somehow its detectng service that definitely arent configured - lol 

I need to roll back those staging changes and rethink this...

**Comment by richardforth** [comment] 2019-02-09 21:04
heres what i have so far

root@ubu1804:~# ps -C varnishd -o rss,command
  RSS COMMAND
 4252 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m


root@ubu1804:~# ps -U vcache -C varnishd -o rss,command
  RSS COMMAND
 4252 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
 6048 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

the problem is that I really dont want to "assume" the username

ideally i'd like to capture the two processes with one single and generic command:

 4252 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
 6048 /usr/sbin/varnishd -j unix,user=vcache -F -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m

**Comment by richardforth** [comment] 2019-02-09 22:14
Ok

I think i may have solved it:


current live script

root@ubu1804:~# curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/master/apache2buddy.pl | perl | grep Varnish
[ -- ] Varnish Detected => Using 4.17 MB of memory.

new staging script

root@ubu1804:~# curl -sL https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl | grep Varnish
[ -- ] Varnish Detected => Using 10.16 MB of memory.


So heres what i had to do:

1. modify the "get_service_memory_usage_mbytes" function so that
2.  if $svc is equal to "varnishd":
3. check if there isa user called "vcache" (using native perl code getpwnam("vcache") function)
4. if found we run a different PPS command that cacptires the vcache user procs
5. of not found, we revert to the standard way of doing things we did before 


heres the old function for reference:


> ```perl
> sub get_service_memory_usage_mbytes {
> 	my ( $svc )  = @_;
> 	my @usage_by_pids = `ps -C $svc -o rss | grep -v RSS`;
> 	our $usage_mbytes = 0;
> 	foreach my $proc (@usage_by_pids) {
> 		our $usage_mbytes += $proc / 1024;
> 	}
> 	our $usage_mbytes = round($usage_mbytes);
> 	return $usage_mbytes;
> }
> ```


new function:

```perl
sub get_service_memory_usage_mbytes {
	my ( $svc )  = @_;
	if ($svc eq "varnishd") {
		# we have to treat varnish somewhat differently due to changes made in 4.1+
		my $vcache_detected = 0;
		# check for the existence of a 'vcache' user, which is the default user of varnish after 4.1
		# checking this way prevents ugly errors
		$vcache_detected = getpwnam("vcache");
		if ( $vcache_detected ) {
			my @usage_by_pids = `ps -U vcache -C varnishd -o rss | grep -v RSS`;
                        our $usage_mbytes = 0;
                        foreach my $proc (@usage_by_pids) {
                                 our $usage_mbytes += $proc / 1024;
                        }
                        our $usage_mbytes = round($usage_mbytes);
                        return $usage_mbytes;
		} else {
			my @usage_by_pids = `ps -C varnishd -o rss | grep -v RSS`;
                	our $usage_mbytes = 0;
                	foreach my $proc (@usage_by_pids) {
                       		 our $usage_mbytes += $proc / 1024;
                	}
                	our $usage_mbytes = round($usage_mbytes);
                	return $usage_mbytes;
		}
	} else {
		my @usage_by_pids = `ps -C $svc -o rss | grep -v RSS`;
		our $usage_mbytes = 0;
		foreach my $proc (@usage_by_pids) {
			our $usage_mbytes += $proc / 1024;
		}
		our $usage_mbytes = round($usage_mbytes);
		return $usage_mbytes;
	}
}
```

I have merged it live so you should be good to go now.

Let me know if you have any problems.

(and sorry for the mix up earlier)

Kind Regards
Richard

**Closed** 2019-02-09 22:13 UTC

**Comment by dthielking** [comment] 2019-02-10 06:48
So great! Thank you. I tested it and it shows the correct values for Varnish and Apache.
