### ISSUE TITLE
Check environment variables when reading conf files

### ISSUE THREAD

**Issue by joelpittet** [richardforth/apache2buddy#14] opened 2016-08-26 22:08 UTC
Working at the University we have some config that is system dependant so we are using environment variables to change paths but they are ignored while reading the conf files currently it seems.

Example:
```
<IFDefine RHE>
  ServerRoot /etc/httpd
</IFDefine>

<IFDefine SUSE>
  ServerRoot /etc/apache2
</IfDefine>
```

Any chance this can be parsed instead of scanned?

**Comment by richardforth** [comment] 2016-08-27 02:56
I would need a bit more information about your setup here. At the moment I
am pretty confident that the ifdefine blocks are ignored.

The code based on the original apachbuddy. All I really did was added new
features.

I can't promise anything but I will definitely take a look.

I just need to understand more about the environment variables how and
where they are set and see if it is possible to parse without a massive
re-write which I really cannot commit to at this time.

If you think you can assist please make a pull request and I will look at
merging your changes. But please bear in mind this has to work across
multiple distributions, though. Thus the complexity level increases.

**Comment by richardforth** [comment] 2016-08-27 04:04
Had a think and First I need to document the process of how currently
apache2buddy.pl is getting a given directive out from the configuration.

Once I have a clear understanding of the current process I can decide if
it's possible to change the behaviour to include ifdefine blocks and only
if the blocks' variable is defined.

One prerequisite therefore is a preflight check to pull all the environment
variables defined in apache. This may be tricky if for example an
environment variable is defined on the command line.

The other tricky concept is SetEnvIf because that too needs parsing to
evaluate true or false which we may not be able to determine outside of
apache runtime.

The likely scenario is that SetEnvIf will still be ignored as we will only
be able to parse OPTIONS as in OPTIONS="-DSLAVE" from /etc/sysconfig/httpd
(Redhat/CentOS) or search for any SetEnv directives.

I'm not dismissing this outright but it does seem that parsing is a
paradigm shift in the way that configurations are read in.

Will document the current process and see how I can collect environment
variables into an array to be checked against later.

If you are able to shed some light on how you are currently set up and why
this was needed over standard setup this will help me understand the impact.

Due to time constraints the best thing is if you are able to contribute via
pull request I'm willing to review and merge.

I will update with more information once I have reviewed the current code.

**Comment by richardforth** [comment] 2016-08-27 11:33
I found the code that deals with this is between lines 471 and 587 as of this writing, but I will need help with the pulling of environment variables and checking or ignoring  the IfDefine Blocks against the environment variables, reliably, across distributions.

Adding the help wanted tag.

As it does seem like a bug (omission) I have tagged it as a bug also.

**Comment by richardforth** [comment] 2016-08-27 11:48
Looking at how this works, I doubt very much we can "parse" the files like apache does, we may need to just be a bit clever with coding something up to do something similar, for example:

1) Get a list of all the environment variables set within apache  (options or setenv only, as setenvif is going to be impossible to evaluate)
2) Check for an IfDefine block
3) Manually try to evaluate the IfDefine to true or false
4) Decide to either Evaluate the block or Dismiss it.

Sounds really easy on paper but having a hard time getting my head round how to code this up.

**Comment by richardforth** [comment] 2016-08-27 12:06
note-to-self

http://www.perlmonks.org/?node_id=746642

needs testing

**Comment by richardforth** [comment] 2016-08-27 12:16
seems like theperlmonks link was discussing a CGI application, I need to get these from CLI with native perl. We cany rely on modules that are not standard because that will limit execution

**Comment by richardforth** [comment] 2016-08-27 12:29
Was playing with php cli phpinfo() but realised this is outside of apache so we cant pull the apache environment variables from there.

**Comment by joelpittet** [comment] 2016-08-28 15:08
Thank you for considering this. I'll do some investigation to how/where these are set at work tomorrow or Tuesday.

Parsing Apache conf may be tricky for sure from a quick look around.

The small config changes we make are new to me but look to help share config between redhat and suse and their subtle file location changes

**Comment by richardforth** [comment] 2016-08-28 15:16
OK cool

Yeah that makes sense. Apache buddy relies heavily on stock installations.

This one is definitely an edge case. Apachebuddy.pl (from where
apache2buddy.pl was forged) have been running in the wild now for at least
5 years or so. Apache2buddy.pl is about 18 months old and based on the old
code which is pretty stable.

That said it does seem logical to try and get the 'correct' configuration.
So it would make sense if we could figure this one out without breaking
things.

I look forward to seeing your updates.

Rich

**Comment by richardforth** [comment] 2016-09-08 20:13
Hi,

I've give this specific issue some more thought and i will explain why I removed the bug and replaced it with 'not a bug' and also for the wontfix label:

This list is by no means prioritised so please dont think number 1 is a primary reason or anything, each one carries its own merit, and while some may not warrant this on their ow, collectively it becomes clear this is unfixable:

1. This project inherits code from apachebuddy.pl, the original pachebuddy project
2. This was never an issue in that project.
3. This wasnt an issue in this project untill raised now, and the project is now quite mature
4. Previous sections of code i quoted, assume that we are looking for a key : value pare in the configuration files and displaying those, however, what apache does in terms of where the main config file, is a bit of guesswork based on the default locations of the main configs in variouls packaged versions of apache, as installed by yum or RPM.

Here is the offending code (lines 1492 - 1495):

	# check 10
	# find the apache configuration file (relative to the apache root)
	our $apache_conf_file = get_apache_conf_file($process_name);
	print "VERBOSE: The Apache config file is: ".$apache_conf_file."\n" if $VERBOSE;


The function THAT code calls looks like this (found at line 788  through 809):

# this will return the apache configuration file, relative to the apache root
# for the provided apache binary
sub get_apache_conf_file {
	our $apache_conf_file;
	my ( $process_name ) = @_;
	if ( $process_name eq "/usr/sbin/apache2") {
		# use apache2ctl instead ...
		$apache_conf_file = `apache2ctl -V 2>&1 | grep \"SERVER_CONFIG_FILE\"`;
		$apache_conf_file =~ s/.*=\"(.*)\"/$1/;
		chomp($apache_conf_file);
	} else {
		$apache_conf_file = `$process_name -V 2>&1 | grep \"SERVER_CONFIG_FILE\"`;
		$apache_conf_file =~ s/.*=\"(.*)\"/$1/;
		chomp($apache_conf_file);
	}
	# return the apache configuration file, or 0 if there is no result
	if ( $apache_conf_file eq '' ) {
		$apache_conf_file = 0;
	}

	return $apache_conf_file;
}


So its actually getting the correct loaded conf file byy running these commands:

Ubuntu:
apache2ctl -V 2>&1 | grep "SERVER_CONFIG_FILE"

RedHat: 
/usr/bin/httpd -V 2>&1 | grep "SERVER_CONFIG_FILE"

or 

/usr/local/bin/httpd -V 2>&1 | grep "SERVER_CONFIG_FILE"

In either case we are not at this stage parsing any configs to get the apache main config file, we are getting this from the main executable, hence, this is actually not a bug, and not something I can easily fix for an edge case.

If you feel this isnt adequately addressed, please raise a new issue and specify the following information:

1. How apache was installed (yum / apt / compiled)
Please note that compiled form source apache installations are not supported in apache2buddy.pl

2. Exactly how you are setting your apache config file paths, that differ from the norm, again if this is something you have compiled in I would need an example command like 

/usr/local/bin/httpd -V 2>&1 | grep "SERVER_CONFIG_FILE"

So that I can pull this reliably, perhaps by adding another if statement to the function I referenced at lines 788 through 809.

I hope that makes sense,

I am closing this issue now as I cant seem to get past it, Feel free to raise another issue with the information I requested and i will look into it again for you.

Best regards
Richard

**Closed by richardforth** 2016-09-08 20:13 UTC
Labels: not_a_bug, wontfix

**Comment by joelpittet** [comment] 2016-09-08 21:38
Thanks for considering this again. I think we can maybe find some work around where we stop the ENV variables. 

My solution to get things working posthaste was to delete those environment variables from the config files that failed to load other files (anything with `<IFDefine SUSE>` in this instance) and was able to get around the problem, and our configuration system just overwrites my changes on the hour anyway.
